# Generated by Django 2.2.7 on 2019-12-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0005_movie_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('release_date', models.DateField()),
                ('number_of_songs', models.IntegerField()),
                ('indiziert', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('dead', models.BooleanField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('genre', models.CharField(choices=[('p', 'Pop'), ('j', 'Jazz'), ('r', 'Rock'), ('h', 'Hip-Hop'), ('v', 'Volksmusic')], max_length=1, null=True)),
                ('length', models.IntegerField()),
                ('album', models.ManyToManyField(blank=True, to='yamod.Album')),
                ('artist', models.ManyToManyField(to='yamod.Artist')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.ManyToManyField(blank=True, to='yamod.Artist'),
        ),
    ]
