# Generated by Django 2.2.7 on 2019-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0008_auto_20191218_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.PositiveIntegerField(help_text='in Minutes'),
        ),
    ]
