# Generated by Django 2.2.7 on 2019-12-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0011_auto_20191218_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('u', 'Unknown'), ('p', 'Pop'), ('j', 'Jazz'), ('r', 'Rock'), ('h', 'Hip-Hop'), ('v', 'Volksmusic')], max_length=1, null=True),
        ),
    ]
