# Generated by Django 2.2.7 on 2019-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0012_auto_20191218_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('over_18', models.BooleanField()),
                ('artists', models.ManyToManyField(blank=True, to='yamod.Artist')),
            ],
        ),
    ]
