# Generated by Django 2.2.7 on 2020-01-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0013_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Concert',
        ),
    ]
