# Generated by Django 2.2.7 on 2020-01-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0016_auto_20200112_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='over_18',
            field=models.BooleanField(null=True),
        ),
    ]
