# Generated by Django 2.2.7 on 2020-01-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0017_auto_20200112_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='yamod.Artist'),
        ),
    ]
