# Generated by Django 2.2.7 on 2020-01-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yamod', '0019_auto_20200112_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(blank=True, to='yamod.Album'),
        ),
    ]
